<template>
  <div>
    <Banner img="img/backgrounds/andy-hyd.jpg" title="Automated data ingestion" subTitle="Data Ingestion using Automated Data Pipelines. Capable of Generating Millions of Pipelines Automatically." />
    <div class="max-w-7xl mx-auto my-16">
      <v-card class="my-4">
        <h1 class="p-8 text-2xl font-bold text-gray-900 text-center">
          Data ingestion is not just data acquisition, it's about prepping the data for curation
        </h1>
        <v-img src="img/backgrounds/Ingestion-processes.png"></v-img>
      </v-card>
    </div>
    <FeatureCard :feature="feature1" />
  </div>
</template>

<script>
import Banner from '@/components/common/Banner'
// import TextCard from '@/components/common/TextCard'
import FeatureCard from '@/components/common/FeatureCard'
export default {
  name: 'ManagedDataops',
  components: {
    Banner,
    // TextCard,
    FeatureCard
  },
  data () {
    return {
      feature1: {
        img: 'img/backgrounds/pipelines.png',
        dir: 'left',
        title: '',
        description: 'When Ingesting huge data into the Data Lake, most projects need to generate approx. half a million of pipelines which is time consuming. Moreover, generating a pipeline manually requires 2 hours. This leads to increase in implementation time. At Modak Analytics, pipelines are generated by Modak’s Internal Proprietary tools in less than a minute. Hence, Modak can ingest huge amount of data in a short span of time and reduce the implementation time.',
        items: []
      }
    }    
  }
};
</script>

<style lang="scss" scoped>
</style>